/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GenerateResponse = shared.AgentResult | shared.HTTPValidationError;

/** @internal */
export const GenerateResponse$inboundSchema: z.ZodType<
  GenerateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.AgentResult$inboundSchema,
  shared.HTTPValidationError$inboundSchema,
]);

/** @internal */
export type GenerateResponse$Outbound =
  | shared.AgentResult$Outbound
  | shared.HTTPValidationError$Outbound;

/** @internal */
export const GenerateResponse$outboundSchema: z.ZodType<
  GenerateResponse$Outbound,
  z.ZodTypeDef,
  GenerateResponse
> = z.union([
  shared.AgentResult$outboundSchema,
  shared.HTTPValidationError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GenerateResponse$ {
  /** @deprecated use `GenerateResponse$inboundSchema` instead. */
  export const inboundSchema = GenerateResponse$inboundSchema;
  /** @deprecated use `GenerateResponse$outboundSchema` instead. */
  export const outboundSchema = GenerateResponse$outboundSchema;
  /** @deprecated use `GenerateResponse$Outbound` instead. */
  export type Outbound = GenerateResponse$Outbound;
}

export function generateResponseToJSON(
  generateResponse: GenerateResponse,
): string {
  return JSON.stringify(
    GenerateResponse$outboundSchema.parse(generateResponse),
  );
}

export function generateResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenerateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerateResponse' from JSON`,
  );
}
