"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING, Literal, TypeAlias, TypeVar

from pydantic import BaseModel as PydanticBaseModel
from pydantic import ConfigDict, model_serializer
from typing_extensions import TypeAliasType


class BaseModel(PydanticBaseModel):
    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True, protected_namespaces=())


class Unset(BaseModel):
    @model_serializer(mode="plain")
    def serialize_model(self):
        return UNSET_SENTINEL

    def __bool__(self) -> Literal[False]:
        return False


UNSET = Unset()
UNSET_SENTINEL = "~?~unset~?~sentinel~?~"


T = TypeVar("T")
if TYPE_CHECKING:
    Nullable: TypeAlias = T | None
    OptionalNullable: TypeAlias = Nullable[T] | None | Unset
else:
    Nullable = TypeAliasType("Nullable", T | None, type_params=(T,))
    OptionalNullable = TypeAliasType("OptionalNullable", Nullable[T] | None | Unset, type_params=(T,))

UnrecognizedInt: TypeAlias = int
UnrecognizedStr: TypeAlias = str
