github: [Bosaj, startlingadama, IdrHamza, Chaymaadihaji]
custom: ["https://github.com/sponsors/Bosaj", "https://github.com/startlingadama", "https://github.com/IdrHamza", "https://github.com/Chaymaadihaji"]
