/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the openapi SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx generate.ts
 */

import { SDK } from "openapi";

const sdk = new SDK({
  serverURL: "https://api.example.com",
});

async function main() {
  const result = await sdk.generate({
    reglements: [],
  });

  console.log(result);
}

main().catch(console.error);
