"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

import httpx

from checkplan_client.errors import SDKBaseError
from checkplan_client.models import validationerror as models_validationerror
from checkplan_client.types import BaseModel


class HTTPValidationErrorData(BaseModel):
    detail: list[models_validationerror.ValidationError] | None = None


class HTTPValidationError(SDKBaseError):
    data: HTTPValidationErrorData

    def __init__(
        self,
        data: HTTPValidationErrorData,
        raw_response: httpx.Response,
        body: str | None = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
