/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AgentResult = {
  maxPages: number;
  maxRgs: number;
  outputFile: string;
  rgPath: string;
};

/** @internal */
export const AgentResult$inboundSchema: z.ZodType<
  AgentResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  max_pages: z.number().int(),
  max_rgs: z.number().int(),
  output_file: z.string(),
  rg_path: z.string(),
}).transform((v) => {
  return remap$(v, {
    "max_pages": "maxPages",
    "max_rgs": "maxRgs",
    "output_file": "outputFile",
    "rg_path": "rgPath",
  });
});

/** @internal */
export type AgentResult$Outbound = {
  max_pages: number;
  max_rgs: number;
  output_file: string;
  rg_path: string;
};

/** @internal */
export const AgentResult$outboundSchema: z.ZodType<
  AgentResult$Outbound,
  z.ZodTypeDef,
  AgentResult
> = z.object({
  maxPages: z.number().int(),
  maxRgs: z.number().int(),
  outputFile: z.string(),
  rgPath: z.string(),
}).transform((v) => {
  return remap$(v, {
    maxPages: "max_pages",
    maxRgs: "max_rgs",
    outputFile: "output_file",
    rgPath: "rg_path",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentResult$ {
  /** @deprecated use `AgentResult$inboundSchema` instead. */
  export const inboundSchema = AgentResult$inboundSchema;
  /** @deprecated use `AgentResult$outboundSchema` instead. */
  export const outboundSchema = AgentResult$outboundSchema;
  /** @deprecated use `AgentResult$Outbound` instead. */
  export type Outbound = AgentResult$Outbound;
}

export function agentResultToJSON(agentResult: AgentResult): string {
  return JSON.stringify(AgentResult$outboundSchema.parse(agentResult));
}

export function agentResultFromJSON(
  jsonString: string,
): SafeParseResult<AgentResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentResult' from JSON`,
  );
}
