/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Reglements = {
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
  fileName: string;
};

export type BodyCheckPlanGeneratorGeneratePost = {
  reglements: Array<Reglements>;
};

/** @internal */
export const Reglements$inboundSchema: z.ZodType<
  Reglements,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
  fileName: z.string(),
});

/** @internal */
export type Reglements$Outbound = {
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
  fileName: string;
};

/** @internal */
export const Reglements$outboundSchema: z.ZodType<
  Reglements$Outbound,
  z.ZodTypeDef,
  Reglements
> = z.object({
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
  fileName: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Reglements$ {
  /** @deprecated use `Reglements$inboundSchema` instead. */
  export const inboundSchema = Reglements$inboundSchema;
  /** @deprecated use `Reglements$outboundSchema` instead. */
  export const outboundSchema = Reglements$outboundSchema;
  /** @deprecated use `Reglements$Outbound` instead. */
  export type Outbound = Reglements$Outbound;
}

export function reglementsToJSON(reglements: Reglements): string {
  return JSON.stringify(Reglements$outboundSchema.parse(reglements));
}

export function reglementsFromJSON(
  jsonString: string,
): SafeParseResult<Reglements, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Reglements$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Reglements' from JSON`,
  );
}

/** @internal */
export const BodyCheckPlanGeneratorGeneratePost$inboundSchema: z.ZodType<
  BodyCheckPlanGeneratorGeneratePost,
  z.ZodTypeDef,
  unknown
> = z.object({
  reglements: z.array(z.lazy(() => Reglements$inboundSchema)),
});

/** @internal */
export type BodyCheckPlanGeneratorGeneratePost$Outbound = {
  reglements: Array<Reglements$Outbound>;
};

/** @internal */
export const BodyCheckPlanGeneratorGeneratePost$outboundSchema: z.ZodType<
  BodyCheckPlanGeneratorGeneratePost$Outbound,
  z.ZodTypeDef,
  BodyCheckPlanGeneratorGeneratePost
> = z.object({
  reglements: z.array(z.lazy(() => Reglements$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BodyCheckPlanGeneratorGeneratePost$ {
  /** @deprecated use `BodyCheckPlanGeneratorGeneratePost$inboundSchema` instead. */
  export const inboundSchema = BodyCheckPlanGeneratorGeneratePost$inboundSchema;
  /** @deprecated use `BodyCheckPlanGeneratorGeneratePost$outboundSchema` instead. */
  export const outboundSchema =
    BodyCheckPlanGeneratorGeneratePost$outboundSchema;
  /** @deprecated use `BodyCheckPlanGeneratorGeneratePost$Outbound` instead. */
  export type Outbound = BodyCheckPlanGeneratorGeneratePost$Outbound;
}

export function bodyCheckPlanGeneratorGeneratePostToJSON(
  bodyCheckPlanGeneratorGeneratePost: BodyCheckPlanGeneratorGeneratePost,
): string {
  return JSON.stringify(
    BodyCheckPlanGeneratorGeneratePost$outboundSchema.parse(
      bodyCheckPlanGeneratorGeneratePost,
    ),
  );
}

export function bodyCheckPlanGeneratorGeneratePostFromJSON(
  jsonString: string,
): SafeParseResult<BodyCheckPlanGeneratorGeneratePost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      BodyCheckPlanGeneratorGeneratePost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BodyCheckPlanGeneratorGeneratePost' from JSON`,
  );
}
