/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type HelloOutput = {
  message?: string | undefined;
};

/** @internal */
export const HelloOutput$inboundSchema: z.ZodType<
  HelloOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  Message: z.string().default(""),
}).transform((v) => {
  return remap$(v, {
    "Message": "message",
  });
});

/** @internal */
export type HelloOutput$Outbound = {
  Message: string;
};

/** @internal */
export const HelloOutput$outboundSchema: z.ZodType<
  HelloOutput$Outbound,
  z.ZodTypeDef,
  HelloOutput
> = z.object({
  message: z.string().default(""),
}).transform((v) => {
  return remap$(v, {
    message: "Message",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HelloOutput$ {
  /** @deprecated use `HelloOutput$inboundSchema` instead. */
  export const inboundSchema = HelloOutput$inboundSchema;
  /** @deprecated use `HelloOutput$outboundSchema` instead. */
  export const outboundSchema = HelloOutput$outboundSchema;
  /** @deprecated use `HelloOutput$Outbound` instead. */
  export type Outbound = HelloOutput$Outbound;
}

export function helloOutputToJSON(helloOutput: HelloOutput): string {
  return JSON.stringify(HelloOutput$outboundSchema.parse(helloOutput));
}

export function helloOutputFromJSON(
  jsonString: string,
): SafeParseResult<HelloOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HelloOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HelloOutput' from JSON`,
  );
}
