/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { generate } from "../funcs/generate.js";
import { hello } from "../funcs/hello.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class SDK extends ClientSDK {
  /**
   * Check Plan Generator
   */
  async generate(
    request: shared.BodyCheckPlanGeneratorGeneratePost,
    options?: RequestOptions,
  ): Promise<operations.GenerateResponse> {
    return unwrapAsync(generate(
      this,
      request,
      options,
    ));
  }

  /**
   * Hello
   */
  async hello(
    options?: RequestOptions,
  ): Promise<shared.HelloOutput> {
    return unwrapAsync(hello(
      this,
      options,
    ));
  }
}
