FROM python:3.11-bullseye

WORKDIR /check-planner

# Install system dependencies
RUN apt-get update && apt-get install -y \
    g++ \
    curl \
    unzip \
    bash \
    jq \
    git \
    tar \
    gcc \
    musl-dev \
    python3-dev \
    libffi-dev \
    openssl \
    build-essential \
    libc-dev \
    man-db \
    groff-base \
    less \
    poppler-utils \
    tesseract-ocr \
    tesseract-ocr-eng \
    tesseract-ocr-fra \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --no-cache-dir --upgrade pip setuptools wheel


COPY requirements.txt .


RUN pip install -r requirements.txt

ENV MODULE_NAME=check_planner \
    ENVIRONMENT=development \
    PYTHONUNBUFFERED=1 \
    OTEL_SDK_DISABLED=true \
    OTEL_TRACES_EXPORTER=none \
    OTEL_METRICS_EXPORTER=none \
    OTEL_LOG_LEVEL=none

COPY . .

EXPOSE 8057
