"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from dataclasses import dataclass

from pydantic import Field

from checkplan_client.types import UNSET, OptionalNullable

from ._version import (
    __gen_version__,
    __openapi_doc_version__,
    __user_agent__,
    __version__,
)
from .httpclient import AsyncHttpClient, HttpClient
from .utils import Logger, RetryConfig, remove_suffix


@dataclass
class SDKConfiguration:
    client: HttpClient | None
    client_supplied: bool
    async_client: AsyncHttpClient | None
    async_client_supplied: bool
    debug_logger: Logger
    server_url: str
    language: str = "python"
    openapi_doc_version: str = __openapi_doc_version__
    sdk_version: str = __version__
    gen_version: str = __gen_version__
    user_agent: str = __user_agent__
    retry_config: OptionalNullable[RetryConfig] = Field(default_factory=lambda: UNSET)
    timeout_ms: int | None = None

    def get_server_details(self) -> tuple[str, dict[str, str]]:
        return remove_suffix(self.server_url, "/"), {}
