"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import builtins
from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .agentresult import AgentResult, AgentResultTypedDict
    from .body_check_plan_generator_generate_post import (
        BodyCheckPlanGeneratorGeneratePost,
        BodyCheckPlanGeneratorGeneratePostTypedDict, Reglements,
        ReglementsTypedDict)
    from .hellooutput import HelloOutput, HelloOutputTypedDict
    from .validationerror import (Loc, LocTypedDict, ValidationError,
                                  ValidationErrorTypedDict)

__all__ = [
    "AgentResult",
    "AgentResultTypedDict",
    "BodyCheckPlanGeneratorGeneratePost",
    "BodyCheckPlanGeneratorGeneratePostTypedDict",
    "HelloOutput",
    "HelloOutputTypedDict",
    "Loc",
    "LocTypedDict",
    "Reglements",
    "ReglementsTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AgentResult": ".agentresult",
    "AgentResultTypedDict": ".agentresult",
    "BodyCheckPlanGeneratorGeneratePost": ".body_check_plan_generator_generate_post",
    "BodyCheckPlanGeneratorGeneratePostTypedDict": ".body_check_plan_generator_generate_post",
    "Reglements": ".body_check_plan_generator_generate_post",
    "ReglementsTypedDict": ".body_check_plan_generator_generate_post",
    "HelloOutput": ".hellooutput",
    "HelloOutputTypedDict": ".hellooutput",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
