"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from checkplan_client.types import BaseModel
from typing_extensions import TypedDict


class AgentResultTypedDict(TypedDict):
    max_pages: int
    max_rgs: int
    output_file: str
    rg_path: str


class AgentResult(BaseModel):
    max_pages: int

    max_rgs: int

    output_file: str

    rg_path: str
