"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

import io
from typing import IO, Annotated, NotRequired

import pydantic
from typing_extensions import TypedDict

from checkplan_client.types import BaseModel
from checkplan_client.utils import FieldMetadata, MultipartFormMetadata


class ReglementsTypedDict(TypedDict):
    content: bytes | IO[bytes] | io.BufferedReader
    file_name: str
    content_type: NotRequired[str]


class Reglements(BaseModel):
    content: Annotated[
        bytes | IO[bytes] | io.BufferedReader,
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    file_name: Annotated[str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)]

    content_type: Annotated[
        str | None,
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None


class BodyCheckPlanGeneratorGeneratePostTypedDict(TypedDict):
    reglements: list[ReglementsTypedDict]


class BodyCheckPlanGeneratorGeneratePost(BaseModel):
    reglements: Annotated[list[Reglements], FieldMetadata(multipart=MultipartFormMetadata(file=True))]
