"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Optional

import pydantic
from checkplan_client.types import BaseModel
from typing_extensions import Annotated, NotRequired, TypedDict


class HelloOutputTypedDict(TypedDict):
    message: NotRequired[str]


class HelloOutput(BaseModel):
    message: Annotated[Optional[str], pydantic.Field(alias="Message")] = ""
