"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, NotRequired

import pydantic
from typing_extensions import TypedDict

from checkplan_client.types import BaseModel


class HelloOutputTypedDict(TypedDict):
    message: NotRequired[str]


class HelloOutput(BaseModel):
    message: Annotated[str | None, pydantic.Field(alias="Message")] = ""
