"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any

import httpx

from checkplan_client import errors

from .serializers import unmarshal_json


def unmarshal_json_response(typ: Any, http_res: httpx.Response, body: str | None = None) -> Any:
    if body is None:
        body = http_res.text
    try:
        return unmarshal_json(body, typ)
    except Exception as e:
        raise errors.ResponseValidationError(
            "Response validation failed",
            http_res,
            e,
            body,
        ) from e
